---
- name: Install required dependencies
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Update apt cache
      raw: apt-get update
      changed_when: false

    - name: Install Python3 packages
      raw: apt-get install -y python3 python3-pip python3-setuptools python3-six
      changed_when: false

    - name: Create ansible module_utils directory
      raw: mkdir -p /usr/lib/python3/dist-packages/ansible/module_utils
      changed_when: false

    - name: Check if six.py exists in module_utils
      raw: ls -la /usr/lib/python3/dist-packages/ansible/module_utils/six.py || echo "NOT_FOUND"
      register: six_exists
      changed_when: false

    - name: Create symbolic link to six in Ansible module_utils
      raw: |
        if [ "{{ six_exists.stdout }}" == "NOT_FOUND" ]; then
          ln -s /usr/lib/python3/dist-packages/six.py /usr/lib/python3/dist-packages/ansible/module_utils/six.py
          touch /usr/lib/python3/dist-packages/ansible/module_utils/__init__.py
        fi
      changed_when: "'NOT_FOUND' in six_exists.stdout"

    - name: Install six with pip
      raw: pip3 install six
      changed_when: false

    - name: Verify six.moves is available
      raw: python3 -c "from ansible.module_utils.six.moves import urllib; print('six.moves доступен')"
      register: six_moves_test
      changed_when: false

    - name: Debug six.moves test
      raw: echo "{{ six_moves_test.stdout }}"
      changed_when: false 