---
- name: Install required dependencies
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Update apt cache
      raw: apt-get update
      changed_when: false

    - name: Install Python3 packages
      raw: apt-get install -y python3 python3-six python3-setuptools
      changed_when: false

    - name: Check if ansible package is available
      raw: apt-cache search python3-ansible || echo "not found"
      register: ansible_pkg_check
      changed_when: false

    - name: Debug ansible package check
      raw: 'echo "Ansible package check: {{ ansible_pkg_check.stdout }}"'
      changed_when: false

    - name: Create ansible module_utils directory if needed
      raw: |
        mkdir -p /usr/lib/python3/dist-packages/ansible/module_utils
        touch /usr/lib/python3/dist-packages/ansible/module_utils/__init__.py
      changed_when: false

    - name: Check if six.py exists in ansible module_utils
      raw: ls -la /usr/lib/python3/dist-packages/ansible/module_utils/six.py || echo "NOT_FOUND"
      register: six_exists
      changed_when: false

    - name: Debug six.py location
      raw: |
        echo "Checking six.py location..."
        find /usr/lib -name "six.py" | grep -v "ansible-tmp"
      changed_when: false
      register: six_location

    - name: Debug six location result
      raw: 'echo "Six location result: {{ six_location.stdout }}"'
      changed_when: false

    - name: Create symbolic link to six.py
      raw: |
        if [ "{{ six_exists.stdout }}" = "NOT_FOUND" ]; then
          ln -s /usr/lib/python3/dist-packages/six.py /usr/lib/python3/dist-packages/ansible/module_utils/six.py
        fi
      changed_when: "'NOT_FOUND' in six_exists.stdout"

    - name: Create ansible module_utils/six directory
      raw: |
        mkdir -p /usr/lib/python3/dist-packages/ansible/module_utils/six
        touch /usr/lib/python3/dist-packages/ansible/module_utils/six/__init__.py
      changed_when: false

    - name: Create a basic moves.py in ansible module_utils/six
      raw: |
        cat > /usr/lib/python3/dist-packages/ansible/module_utils/six/moves.py << 'EOF'
        from six.moves import *
        EOF
      changed_when: false

    - name: Verify ansible module_utils exists
      raw: ls -la /usr/lib/python3/dist-packages/ansible/module_utils/
      register: ansible_module_utils
      changed_when: false

    - name: Debug ansible module_utils content
      raw: 'echo "{{ ansible_module_utils.stdout }}"'
      changed_when: false

    - name: Try to import six.moves
      raw: python3 -c "import six.moves; print('six.moves доступен')"
      register: six_moves_test
      changed_when: false
      ignore_errors: yes

    - name: Debug six.moves import result
      raw: 'echo "six.moves import result: {{ six_moves_test.stdout }}"'
      changed_when: false

    - name: Try to import ansible.module_utils.six.moves
      raw: python3 -c "import sys; sys.path.append('/usr/lib/python3/dist-packages/'); import ansible.module_utils.six.moves; print('ansible.module_utils.six.moves доступен')"
      register: ansible_six_moves_test
      changed_when: false
      ignore_errors: yes

    - name: Debug ansible.module_utils.six.moves import result
      raw: 'echo "ansible.module_utils.six.moves import result: {{ ansible_six_moves_test.stdout }}"'
      changed_when: false 