---
- name: Install Python and basic packages
  hosts: all
  gather_facts: no
  tasks:
    - name: Install Python 3
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal python3-pip python3-setuptools python3-six)
      changed_when: false

    - name: Install pip packages
      raw: pip3 install six
      changed_when: false

- name: Setup BiHA PostgreSQL cluster
  hosts: all
  become: yes
  roles:
    - common
    - postgrespro
    - biha 