---
- name: Check if Postgres Pro repository exists
  raw: |
    if [ -f "/etc/apt/sources.list.d/postgrespro-ent-{{ postgres_version }}.list" ]; then
      echo "Repository exists"
    else
      echo "Repository does not exist"
    fi
  register: repo_check
  changed_when: false

- name: Remove existing Postgres Pro repository
  raw: |
    if [ -f "/etc/apt/sources.list.d/postgrespro-ent-{{ postgres_version }}.list" ]; then
      rm "/etc/apt/sources.list.d/postgrespro-ent-{{ postgres_version }}.list"
      echo "Repository removed"
    fi
  when: "'Repository exists' in repo_check.stdout"
  changed_when: true

- name: Download Postgres Pro repository script
  raw: |
    wget --user {{ postgres_pro_license }} --password='' {{ postgres_pro_repo_url }} -O /tmp/pgpro-repo-add.sh
    chmod 755 /tmp/pgpro-repo-add.sh
  changed_when: true

- name: Execute repository script
  raw: |
    if [ ! -f "/etc/apt/sources.list.d/postgrespro-ent-{{ postgres_version }}.list" ]; then
      /tmp/pgpro-repo-add.sh
      echo "Repository added"
    fi
  register: repo_result
  changed_when: "'Repository added' in repo_result.stdout"

- name: Update apt cache
  raw: |
    apt-get update
  register: apt_update
  until: apt_update.rc == 0
  retries: 3
  delay: 5
  changed_when: true

- name: Install Postgres Pro Enterprise
  raw: |
    apt-get install -y postgrespro-ent-{{ postgres_version }}-contrib
  register: pg_install
  until: pg_install.rc == 0
  retries: 3
  delay: 10
  changed_when: true

- name: Check installation status
  raw: |
    dpkg-query -W -f='${Status}' postgrespro-ent-{{ postgres_version }}-contrib | grep -q '^install ok installed$'
  register: pg_check
  changed_when: false
  failed_when: pg_check.rc != 0

- name: Initialize database
  raw: |
    if [ ! -f "{{ postgres_data_dir }}/PG_VERSION" ]; then
      {{ postgres_bin_dir }}/pg-setup initdb --tune=1c
      echo "Database initialized"
    fi
  register: init_result
  changed_when: "'Database initialized' in init_result.stdout"

- name: Enable Postgres Pro service
  raw: |
    {{ postgres_bin_dir }}/pg-setup service enable
  register: enable_result
  changed_when: true

- name: Start Postgres Pro service
  raw: |
    systemctl start postgrespro-ent-{{ postgres_version }}
    systemctl enable postgrespro-ent-{{ postgres_version }}
  register: start_result
  until: start_result.rc == 0
  retries: 3
  delay: 5
  changed_when: true 