---
- name: Ensure sudo is installed
  apt:
    name: sudo
    state: present
    update_cache: yes
  when: ansible_os_family in ['Debian', 'AstraLinux']

- name: Ensure iadmin user has sudo privileges
  lineinfile:
    path: /etc/sudoers.d/iadmin
    line: "iadmin ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: '0440'
    validate: 'visudo -cf %s'
  when: ansible_os_family in ['Debian', 'AstraLinux']

- name: Install Python dependencies
  apt:
    name:
      - python3
      - python3-pip
      - python3-setuptools
      - python3-dev
      - python3-six
    state: present
    update_cache: yes
  when: ansible_os_family in ['Debian', 'AstraLinux']

- name: Install required packages
  apt:
    name:
      - wget
      - curl
      - gnupg2
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install required packages for Astra Linux
  apt:
    name:
      - wget
      - curl
      - gnupg2
    state: present
    update_cache: yes
  when: ansible_os_family == "AstraLinux" 