---
- name: Check Python version
  command: python3 --version
  register: python_version
  changed_when: false
  failed_when: false

- name: Install Python 3 if not present
  apt:
    name: python3
    state: present
  when: python_version.rc != 0

- name: Install Python packages
  apt:
    name:
      - python3-pip
      - python3-setuptools
      - python3-six
    state: present
  register: python_packages
  until: python_packages is success
  retries: 3
  delay: 5

- name: Install pip packages
  pip:
    name:
      - six
    state: present
  become: yes
  become_user: root
  when: python_packages is success

- name: Ensure sudo is installed
  apt:
    name: sudo
    state: present
  register: sudo_install
  until: sudo_install is success
  retries: 3
  delay: 5

- name: Configure passwordless sudo for iadmin
  blockinfile:
    path: /etc/sudoers.d/iadmin
    create: yes
    mode: '0440'
    owner: root
    group: root
    block: |
      iadmin ALL=(ALL) NOPASSWD: ALL
      Defaults:iadmin !requiretty

- name: Install locales package
  apt:
    name: locales
    state: present
    update_cache: yes
  when: ansible_os_family in ['Debian', 'AstraLinux']

- name: Generate UTF-8 locale
  locale_gen:
    name: ru_RU.UTF-8
    state: present
  when: ansible_os_family in ['Debian', 'AstraLinux']

- name: Set default locale
  lineinfile:
    path: /etc/default/locale
    line: "{{ item }}"
    create: yes
  with_items:
    - LANG=ru_RU.UTF-8
    - LC_ALL=ru_RU.UTF-8
  when: ansible_os_family in ['Debian', 'AstraLinux']

- name: Install required packages
  apt:
    name:
      - wget
      - curl
      - gnupg2
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install required packages for Astra Linux
  apt:
    name:
      - wget
      - curl
      - gnupg2
    state: present
    update_cache: yes
  when: ansible_os_family == "AstraLinux" 