---
- name: Install Python and dependencies
  raw: |
    if ! command -v python3 >/dev/null 2>&1; then
      apt-get update
      apt-get install -y python3-minimal python3-pip python3-setuptools python3-six
      pip3 install six
    fi
  changed_when: false

- name: Ensure sudo is installed
  raw: |
    if ! command -v sudo >/dev/null 2>&1; then
      apt-get update
      apt-get install -y sudo
    fi
  changed_when: false

- name: Configure passwordless sudo for iadmin
  raw: |
    echo "iadmin ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/iadmin
    echo "Defaults:iadmin !requiretty" >> /etc/sudoers.d/iadmin
    chmod 440 /etc/sudoers.d/iadmin
  changed_when: true

- name: Install locales package
  raw: |
    if ! dpkg -l | grep -q locales; then
      apt-get update
      apt-get install -y locales
    fi
  changed_when: false

- name: Generate UTF-8 locale
  raw: |
    if ! locale -a | grep -q ru_RU.UTF-8; then
      locale-gen ru_RU.UTF-8
    fi
  changed_when: false

- name: Set default locale
  raw: |
    echo "LANG=ru_RU.UTF-8" > /etc/default/locale
    echo "LC_ALL=ru_RU.UTF-8" >> /etc/default/locale
  changed_when: true

- name: Install required packages
  raw: |
    if ! dpkg -l | grep -q wget || ! dpkg -l | grep -q curl || ! dpkg -l | grep -q gnupg2; then
      apt-get update
      apt-get install -y wget curl gnupg2
    fi
  changed_when: false 