---
- name: Stop PostgreSQL service
  raw: |
    systemctl stop postgrespro-ent-{{ postgres_version }}
  register: start_result
  until: start_result.rc == 0
  retries: 3
  delay: 5
  changed_when: true 

- name: Create temp .pgpass file
  raw: bash -c "echo '*:*:*:biha_replication_user:{{ biha_replication_password }}' > /tmp/pgpass"
  changed_when: true
  no_log: true

- name: Set permissions and move .pgpass file
  raw: bash -c "install -m 0600 -o postgres -g postgres /tmp/pgpass /var/lib/postgresql/.pgpass"
  changed_when: true

- name: Clean up temp file
  raw: rm -f /tmp/pgpass
  changed_when: false

- name: Install expect
  become: yes
  raw: apt-get update && apt-get install -y expect
  changed_when: true
  when: node_role == "LEADER"

- name: Initialize BiHA cluster on leader
  become: yes
  become_user: postgres
  raw: |
    expect -c '
      spawn {{ postgres_bin_dir }}/bihactl init --convert \
        --biha-node-id={{ node_id }} \
        --host={{ ansible_host }} \
        --port={{ postgres_port }} \
        --nquorum={{ biha_nquorum }} \
        --minnodes={{ biha_minnodes }} \
        --pgdata=/var/lib/pgpro/ent-{{ postgres_version }}/data
      expect "Please, provide password for biha_replication_user:"
      send "{{ biha_replication_password }}\r"
      expect eof
    '
  args:
    creates: "/var/lib/pgpro/ent-{{ postgres_version }}/data/PG_VERSION"
  register: biha_init
  when: node_role == "LEADER"
  no_log: true

- name: Set magic string fact
  set_fact:
    magic_string: "{{ biha_init.stdout }}"
  when: node_role == "LEADER"

- name: Configure pg_hba.biha.conf
  become: yes
  become_user: postgres
  raw: |
    cat > /var/lib/pgpro/ent-{{ postgres_version }}/data/pg_hba.biha.conf << 'EOF'
    # TYPE  DATABASE        USER                   ADDRESS       METHOD
    host    postgres        biha_replication_user  all           md5
    host    biha_db         biha_replication_user  all           md5
    host    replication     biha_replication_user  all           md5
    EOF
    chmod 600 /var/lib/pgpro/ent-{{ postgres_version }}/data/pg_hba.biha.conf
    chown postgres:postgres /var/lib/pgpro/ent-{{ postgres_version }}/data/pg_hba.biha.conf

- name: Clean data directory for referee and follower
  become: yes
  become_user: postgres
  raw: rm -rf /var/lib/pgpro/ent-{{ postgres_version }}/data/*
  when: node_role in ['REFEREE', 'FOLLOWER']

- name: Add follower to cluster
  become: yes
  become_user: postgres
  raw: |
    {{ postgres_bin_dir }}/bihactl add \
      --biha-node-id={{ node_id }} \
      --host={{ ansible_host }} \
      --port={{ postgres_port }} \
      --biha-port={{ biha_port }} \
      --magic-string="{{ magic_string }}" \
      --pgdata=/var/lib/pgpro/ent-{{ postgres_version }}/data
  when: node_role == "FOLLOWER"
  no_log: true

- name: Add referee to cluster
  become: yes
  become_user: postgres
  raw: |
    {{ postgres_bin_dir }}/bihactl add \
      --biha-node-id={{ node_id }} \
      --host={{ ansible_host }} \
      --port={{ postgres_port }} \
      --biha-port={{ biha_port }} \
      --mode=referee \
      --magic-string="{{ magic_string }}" \
      --pgdata=/var/lib/pgpro/ent-{{ postgres_version }}/data
  when: node_role == "REFEREE"
  no_log: true

- name: Start PostgreSQL service
  systemd:
    name: "postgrespro-ent-{{ postgres_version }}"
    state: started
    enabled: yes
  when: node_role in ['LEADER', 'FOLLOWER', 'REFEREE']

- name: Wait for PostgreSQL to start
  wait_for:
    port: "{{ postgres_port }}"
    timeout: 30
  when: node_role in ['LEADER', 'FOLLOWER', 'REFEREE']

- name: Check BiHA cluster status
  become: yes
  become_user: postgres
  shell: "{{ postgres_bin_dir }}/bihactl status --magic-string={{ magic_string }}"
  register: biha_status
  when: node_role == "LEADER"
  changed_when: false 